services:
  ros:
    image: registry.robotics-lab.ru/robomarvel:v3
    build: .
    container_name: ros
    privileged: true
    ports: [8765:8765, 8080:8080]
    volumes:
      - ".:/src"
      - "/dev:/dev"
      - "/run/udev:/run/udev:ro"
