- hosts: all

  tasks:
    - name: Sync files
      ansible.posix.synchronize:
        archive: true
        mode: push
        src: ../
        dest: /home/robomarvel/robomarvel/
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=ansible.cfg"
          - "--exclude=untracked"

    - name: Pull docker image
      community.docker.docker_compose_v2_pull:
        project_src: /home/robomarvel/robomarvel
